name: pub_dmclcheckgia
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.1
#  connectivity_plus: ^3.0.2
#  dotted_line: ^3.1.0
#  url_launcher: ^6.1.11
#  permission_handler: ^10.0.0
  dio: ^5.2.1+1
  curl_logger_dio_interceptor: ^1.0.0
  pretty_dio_logger: ^1.2.0-beta-1
#  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.15
  intl: ^0.18.0
  cached_network_image: ^3.2.0
  device_info_plus: ^8.2.0
#  qr_code_scanner: ^1.0.1
#  socket_io_client: ^2.0.2
#  # uni_links: ^0.5.1
#  app_links: ^3.4.2
#  firebase_core: ^2.11.0
#  firebase_messaging: ^14.5.0
  ua_client_hints: ^1.1.3
#  local_auth: ^2.1.6
#  modal_bottom_sheet: ^3.0.0-pre
#  android_intent_plus: ^4.0.1
#  flutter_file_downloader: ^1.1.2
  image_picker: ^0.8.7+5
#  animated_text_kit: ^4.2.2
#  external_path: ^1.0.3
#  # open_filex: ^4.3.2
#  android_package_installer: ^0.0.2
#  flutter_app_installer: ^0.0.3
#  path_provider: ^2.0.15
#  flutter_js: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

#  assets:
#    - assets/img/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
